// Share-conversation dialog (ported from the Franklin Desktop app, adapted to
// the web message model). Pick which messages to include, then copy a public
// link, copy them as text, or export a clean image. The link uploads the
// selected snapshot to /api/share (same-origin) and copies the returned
// /s/<id> URL. Tool activity (search queries + tools used) is derived from each
// assistant message's `activity` field and travels with the share so the public
// page reproduces the tool usage too.

import { useMemo, useRef, useState } from "react";
import { toPng } from "html-to-image";
import { Check, Copy, ImageDown, Link2, X } from "lucide-react";
import type { ChatMessage } from "@/hooks/use-franklin-chat";
import { MessageContent } from "./MessageContent";
import { useTryLang } from "@/lib/try-i18n";

// Image-share message cap (Doubao-style). A very tall PNG hits browser canvas
// size limits and degrades; over this many selected bubbles we disable "share
// image" (the link has no such limit, so it stays available).
const IMAGE_SHARE_LIMIT = 30;

// Where the public share snapshot is published. Same-origin on the web.
const SHARE_API = "/api/share";

interface ToolStep {
  label: string;
  detail?: string;
}

const LABELS: Record<string, {
  title: string; cancel: string; all: string; copy: string; copied: string; img: string; busy: string;
  link: string; linking: string; linked: string; linkErr: string;
  previewTitle: string; copyImg: string; copiedImg: string; copyImgFail: string; download: string; heading: string; disclaimer: string;
  imgLimit: (n: number) => string;
}> = {
  en: {
    title: "Select messages", cancel: "Cancel", all: "Select all", copy: "Copy", copied: "Copied", img: "Share image", busy: "Rendering…",
    link: "Copy link", linking: "Creating…", linked: "Link copied", linkErr: "Share failed",
    previewTitle: "Image preview", copyImg: "Copy image", copiedImg: "Copied", copyImgFail: "Copy failed", download: "Download image", heading: "Shared conversation", disclaimer: "Generated by AI · may not be fully accurate",
    imgLimit: (n) => `Over ${n} messages selected — can't share as image`,
  },
  zh: {
    title: "选择对话", cancel: "取消", all: "全选", copy: "复制", copied: "已复制", img: "分享图片", busy: "生成中…",
    link: "复制链接", linking: "生成中…", linked: "链接已复制", linkErr: "分享失败",
    previewTitle: "分享图片预览", copyImg: "复制图片", copiedImg: "已复制", copyImgFail: "复制失败", download: "下载图片", heading: "分享对话", disclaimer: "内容由 AI 生成,不能完全保障真实",
    imgLimit: (n) => `所选对话超过 ${n} 条,无法分享图片`,
  },
  es: {
    title: "Seleccionar mensajes", cancel: "Cancelar", all: "Todos", copy: "Copiar", copied: "Copiado", img: "Compartir imagen", busy: "Generando…",
    link: "Copiar enlace", linking: "Creando…", linked: "Enlace copiado", linkErr: "Error al compartir",
    previewTitle: "Vista previa", copyImg: "Copiar imagen", copiedImg: "Copiado", copyImgFail: "Error al copiar", download: "Descargar imagen", heading: "Conversación compartida", disclaimer: "Generado por IA · puede no ser exacto",
    imgLimit: (n) => `Más de ${n} mensajes seleccionados — no se puede compartir como imagen`,
  },
};

// Localized "2026 年 6 月 5 日" / "June 5, 2026" date for the image header.
function fmtDate(lang: string): string {
  const d = new Date();
  if (lang === "zh") return `${d.getFullYear()} 年 ${d.getMonth() + 1} 月 ${d.getDate()} 日`;
  try {
    return d.toLocaleDateString(lang === "es" ? "es-ES" : "en-US", { year: "numeric", month: "long", day: "numeric" });
  } catch {
    return d.toDateString();
  }
}

async function copyText(text: string): Promise<boolean> {
  try {
    if (navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(text);
      return true;
    }
  } catch { /* fall through */ }
  try {
    const ta = document.createElement("textarea");
    ta.value = text;
    ta.style.position = "fixed";
    ta.style.opacity = "0";
    document.body.appendChild(ta);
    ta.select();
    const ok = document.execCommand("copy");
    document.body.removeChild(ta);
    return ok;
  } catch {
    return false;
  }
}

function msgImages(m: ChatMessage): string[] {
  if (m.images && m.images.length > 0) return m.images;
  if (m.image) return [m.image];
  return [];
}

function mediaTag(m: ChatMessage): string {
  if (m.kind === "image") return "[image]";
  if (m.kind === "video") return "[video]";
  if (m.kind === "music") return "[audio]";
  return "";
}

// Derive shareable tool steps from a web message's `activity` (the web keeps
// tool usage on the assistant message, not as separate "tools" bubbles).
function toolStepsOf(m: ChatMessage): ToolStep[] {
  const a = m.activity;
  if (!a) return [];
  const steps: ToolStep[] = [];
  for (const q of (a.queries ?? []).slice(0, 8)) steps.push({ label: "Search", detail: q });
  for (const tl of a.tools ?? []) steps.push({ label: tl });
  return steps.slice(0, 50);
}

type Entry =
  | { kind: "msg"; m: ChatMessage; key: string }
  | { kind: "tools"; tools: ToolStep[]; key: string };

export function ShareDialog({ messages, onClose }: { messages: ChatMessage[]; onClose: () => void }) {
  const { lang, t } = useTryLang();
  const L = LABELS[lang] ?? LABELS.en;

  // Selectable bubbles: text + media messages (anything with content or media).
  const items = useMemo(
    () => messages.map((m, i) => ({ m, i })).filter((x) => x.m.content || msgImages(x.m).length > 0 || x.m.video || x.m.music),
    [messages],
  );
  const [sel, setSel] = useState<Set<number>>(() => new Set(items.map((x) => x.i)));
  const [copied, setCopied] = useState(false);
  const [busy, setBusy] = useState(false);
  const [linkState, setLinkState] = useState<"idle" | "busy" | "done" | "error">("idle");
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const [imgCopy, setImgCopy] = useState<"idle" | "done" | "fail">("idle");
  const previewRef = useRef<HTMLDivElement>(null);

  const allSel = items.length > 0 && sel.size === items.length;
  const selected = items.filter((x) => sel.has(x.i));
  const overImgLimit = selected.length > IMAGE_SHARE_LIMIT;

  // What actually travels (link snapshot + exported image): each selected
  // message, preceded by a tool block derived from its activity (so the share
  // reproduces tool usage in order, not just the prose).
  const entries = useMemo<Entry[]>(() => {
    const out: Entry[] = [];
    messages.forEach((m, i) => {
      if (!sel.has(i)) return;
      const ts = m.role === "assistant" ? toolStepsOf(m) : [];
      if (ts.length) out.push({ kind: "tools", tools: ts, key: `t-${i}` });
      out.push({ kind: "msg", m, key: `m-${i}` });
    });
    return out;
  }, [messages, sel]);

  const toggle = (i: number) =>
    setSel((s) => {
      const n = new Set(s);
      if (n.has(i)) n.delete(i);
      else n.add(i);
      return n;
    });
  const toggleAll = () => setSel(allSel ? new Set() : new Set(items.map((x) => x.i)));

  const onCopy = async () => {
    const md = selected
      .map(({ m }) => `${m.role === "user" ? "You" : "Franklin"}: ${m.content || mediaTag(m)}`)
      .join("\n\n");
    if (await copyText(md)) {
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    }
  };

  // Render the selected messages to a PNG and OPEN A PREVIEW — don't jump
  // straight to a download. The user then picks copy or download.
  const onExport = async () => {
    const node = previewRef.current;
    if (!node || selected.length === 0) return;
    setBusy(true);
    try {
      const bg = getComputedStyle(document.documentElement).getPropertyValue("--bg").trim() || "#ffffff";
      try { await (document as Document & { fonts?: { ready: Promise<unknown> } }).fonts?.ready; } catch { /* noop */ }
      await Promise.all(
        Array.from(node.querySelectorAll("img")).map((img) =>
          img.complete ? Promise.resolve() : img.decode().catch(() => undefined),
        ),
      );
      const width = node.scrollWidth;
      const height = node.scrollHeight;
      // Browsers cap canvas dimensions (~16k px). A tall chat × pixelRatio 2
      // easily blows past that and gets cropped — scale the ratio down to fit.
      const MAX = 16000;
      const ratio = Math.max(1, Math.min(2, MAX / height, MAX / width));
      const dataUrl = await toPng(node, {
        pixelRatio: ratio,
        backgroundColor: bg,
        cacheBust: true,
        width,
        height,
        style: { width: `${width}px`, height: `${height}px` },
      });
      setPreviewUrl(dataUrl);
    } catch {
      /* ignore */
    } finally {
      setBusy(false);
    }
  };

  const onDownloadImg = () => {
    if (!previewUrl) return;
    const a = document.createElement("a");
    a.href = previewUrl;
    a.download = "franklin-chat.png";
    a.click();
  };

  const onCopyImg = async () => {
    if (!previewUrl) return;
    let ok = false;
    if (navigator.clipboard && "write" in navigator.clipboard) {
      try {
        const blob = await (await fetch(previewUrl)).blob();
        await navigator.clipboard.write([new ClipboardItem({ "image/png": blob })]);
        ok = true;
      } catch {
        ok = false;
      }
    }
    setImgCopy(ok ? "done" : "fail");
    setTimeout(() => setImgCopy("idle"), 1800);
  };

  const onShareLink = async () => {
    if (selected.length === 0 || linkState === "busy") return;
    setLinkState("busy");
    try {
      const payload = {
        title: selected.find((x) => x.m.role === "user")?.m.content?.slice(0, 80) || "Franklin chat",
        messages: entries.map((e) =>
          e.kind === "tools"
            ? { role: "assistant" as const, content: "", kind: "tools" as const, tools: e.tools }
            : {
                role: e.m.role,
                content: e.m.content,
                kind: e.m.kind,
                // Only inline data: images travel (remote/local media is stripped
                // server-side anyway).
                image: msgImages(e.m).find((u) => u.startsWith("data:")),
              },
        ),
      };
      const res = await fetch(SHARE_API, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const { url } = (await res.json()) as { url?: string };
      if (url && (await copyText(url))) {
        setLinkState("done");
        setTimeout(() => setLinkState("idle"), 2000);
      } else {
        throw new Error("no url");
      }
    } catch {
      setLinkState("error");
      setTimeout(() => setLinkState("idle"), 2000);
    }
  };

  const renderTools = (tools: ToolStep[], key: string) => (
    <div key={key} className="try-share-tools">
      <div className="try-share-tools-head">{t.activityUsed(tools.length)}</div>
      {tools.map((s, k) => (
        <div key={k} className="try-share-tools-row">
          <span className="try-share-tools-label">{s.label}</span>
          {s.detail && <span className="try-share-tools-detail">{s.detail}</span>}
        </div>
      ))}
    </div>
  );

  const renderMsg = (m: ChatMessage, key: string) => {
    const imgs = msgImages(m);
    return (
      <div key={key} className={`try-msg try-msg-${m.role}`}>
        <div className="try-msg-role">{m.role === "user" ? "You" : "Franklin"}</div>
        {m.kind === "image" && imgs.length ? (
          <div className="try-msg-media">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={imgs[0]} alt="" />
          </div>
        ) : m.kind === "video" && m.video ? (
          <div className="try-msg-media"><video src={m.video} controls /></div>
        ) : m.kind === "music" && m.music ? (
          <div className="try-msg-media try-msg-audio"><audio src={m.music} controls /></div>
        ) : imgs.length ? (
          <>
            <div className="try-msg-media">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={imgs[0]} alt="" />
          </div>
            {m.content && <div className="try-msg-body">{m.content}</div>}
          </>
        ) : (
          <div className="try-msg-body">
            {m.role === "assistant" ? <MessageContent content={m.content} /> : m.content}
          </div>
        )}
      </div>
    );
  };

  const renderEntry = (e: Entry) => (e.kind === "tools" ? renderTools(e.tools, e.key) : renderMsg(e.m, e.key));

  return (
    <div className="try-share-overlay" onClick={onClose} role="dialog" aria-modal="true">
      <div className="try-share-modal" onClick={(e) => e.stopPropagation()}>
        <div className="try-share-head">
          <span className="try-share-title">{L.title}</span>
          <button className="try-share-cancel" onClick={onClose}>{L.cancel}</button>
        </div>

        <div className="try-share-list">
          {items.map(({ m, i }) => (
            <button key={i} className={`try-share-item${sel.has(i) ? " is-on" : ""}`} onClick={() => toggle(i)}>
              <span className={`try-share-check${sel.has(i) ? " is-on" : ""}`}>{sel.has(i) && <Check className="h-3.5 w-3.5" />}</span>
              <div className="try-share-item-body">{renderMsg(m, `it-${i}`)}</div>
            </button>
          ))}
        </div>

        <div className="try-share-foot">
          <button className="try-share-all" onClick={toggleAll}>
            <span className={`try-share-check${allSel ? " is-on" : ""}`}>{allSel && <Check className="h-3.5 w-3.5" />}</span>
            {L.all}
          </button>
          <div className="try-share-actions">
            <button className="try-share-btn" onClick={onCopy} disabled={selected.length === 0}>
              {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
              {copied ? L.copied : L.copy}
            </button>
            <span title={overImgLimit ? L.imgLimit(IMAGE_SHARE_LIMIT) : undefined} style={{ display: "inline-flex" }}>
              <button className="try-share-btn" onClick={onExport} disabled={selected.length === 0 || busy || overImgLimit}>
                <ImageDown className="h-4 w-4" />
                {busy ? L.busy : L.img}
              </button>
            </span>
            <button className="try-share-btn is-primary" onClick={onShareLink} disabled={selected.length === 0 || linkState === "busy"}>
              {linkState === "done" ? <Check className="h-4 w-4" /> : <Link2 className="h-4 w-4" />}
              {linkState === "busy" ? L.linking : linkState === "done" ? L.linked : linkState === "error" ? L.linkErr : L.link}
            </button>
          </div>
        </div>
      </div>

      {/* Off-screen render target for the exported image. */}
      <div className="try-share-capture" aria-hidden>
        <div ref={previewRef} className="try-share-canvas">
          <div className="try-share-canvas-head">
            <div className="try-share-canvas-title">{L.heading}</div>
            <div className="try-share-canvas-meta">{fmtDate(lang)} · {L.disclaimer}</div>
          </div>
          <div className="try-share-canvas-rule" />
          {entries.map(renderEntry)}
        </div>
      </div>

      {/* Image preview — shown BEFORE saving, so the user copies or downloads. */}
      {previewUrl && (
        <div className="try-imgpreview-overlay" onClick={() => setPreviewUrl(null)} role="dialog" aria-modal="true">
          <div className="try-imgpreview-modal" onClick={(e) => e.stopPropagation()}>
            <div className="try-share-head">
              <span className="try-share-title">{L.previewTitle}</span>
              <button className="try-imgpreview-x" onClick={() => setPreviewUrl(null)} aria-label={L.cancel}>
                <X className="h-[18px] w-[18px]" />
              </button>
            </div>
            <div className="try-imgpreview-body">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img className="try-imgpreview-img" src={previewUrl} alt="" />
            </div>
            <div className="try-imgpreview-foot">
              <button className="try-share-btn" onClick={onCopyImg}>
                {imgCopy === "done" ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                {imgCopy === "done" ? L.copiedImg : imgCopy === "fail" ? L.copyImgFail : L.copyImg}
              </button>
              <button className="try-share-btn is-primary" onClick={onDownloadImg}>
                <ImageDown className="h-4 w-4" />
                {L.download}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
