import assert from "node:assert/strict";
import { NextRequest } from "next/server";
import { GET as login } from "../src/app/api/try/account/login/route.ts";
import { GET as callback } from "../src/app/api/try/account/callback/route.ts";
import { POST as proxy, GET as proxyGet } from "../src/app/api/blockrun/[...path]/route.ts";
import { ACCOUNT_COOKIE, LOGIN_COOKIE, readAccountSession, readLoginState, sealAccountData } from "../src/lib/blockrun-account.ts";
process.env.SESSION_SECRET = "test-account-routes-secret-at-least-32-bytes";
const originalFetch = globalThis.fetch;
const calls: { url: string; init: RequestInit | undefined }[] = [];
let reply = () => Response.json({ ok: true });
globalThis.fetch = (async (url: string | URL | Request, init?: RequestInit) => { calls.push({ url: String(url), init }); return reply(); }) as typeof fetch;
try {
  const start = await login(new NextRequest("https://franklin.run/api/try/account/login"));
  const location = new URL(start.headers.get("location")!);
  assert.equal(location.origin, "https://user.blockrun.ai");
  assert.equal(location.pathname, "/api/franklin/authorize");
  assert.equal(location.searchParams.get("code_challenge_method"), "S256");
  const loginCookie = start.cookies.get(LOGIN_COOKIE)!.value;
  const state = readLoginState(loginCookie)!;
  assert.equal(state.state, location.searchParams.get("state"));
  const callbackUrl = `https://franklin.run/api/try/account/callback?code=${"c".repeat(43)}&state=${state.state}`;
  const accessToken = "brk_live_" + "a".repeat(40);
  reply = () => Response.json({ access_token: accessToken, expires_in: 28800, email: "member@example.test" });
  const returned = await callback(new NextRequest(callbackUrl, { headers: { cookie: `${LOGIN_COOKIE}=${loginCookie}` } }));
  assert.equal(returned.headers.get("location"), "https://franklin.run/chat?account_connected=1");
  const accountCookie = returned.cookies.get(ACCOUNT_COOKIE)!.value;
  assert.equal(readAccountSession(accountCookie)!.accessToken, accessToken);
  assert.ok(returned.headers.get("set-cookie")!.includes("HttpOnly"));
  assert.ok(returned.headers.get("set-cookie")!.includes("Secure"));
  assert.equal(JSON.parse(calls[0].init!.body as string).code_verifier, state.verifier);
  calls.length = 0;
  await callback(new NextRequest(callbackUrl.replace(state.state, "wrong"), { headers: { cookie: `${LOGIN_COOKIE}=${loginCookie}` } }));
  assert.equal(calls.length, 0, "mismatched state must not exchange any code");
  const headers = { "content-type": "application/json", origin: "https://franklin.run", cookie: `${ACCOUNT_COOKIE}=${accountCookie}`, "x-franklin-payment": "credit" };
  const context = { params: Promise.resolve({ path: ["v1", "messages"] }) };
  reply = () => new Response('event: message_stop\ndata: {}\n\n', { headers: { "Content-Type": "text/event-stream", "x-blockrun-credit-remaining-usd": "2.5" } });
  const answer = await proxy(new NextRequest("https://franklin.run/api/blockrun/v1/messages", { method: "POST", headers: { ...headers, "x-blockrun-chain": "solana" }, body: '{"stream":true}' }), context);
  assert.equal(calls[0].url, "https://api.blockrun.ai/v1/messages");
  assert.equal(new Headers(calls[0].init!.headers).get("authorization"), `Bearer ${accessToken}`);
  assert.equal(new Headers(calls[0].init!.headers).get("x-payment"), null);
  assert.equal(answer.headers.get("content-type"), "text/event-stream");
  assert.equal(answer.headers.get("x-blockrun-credit-remaining-usd"), "2.5");
  assert.ok((await answer.text()).includes("message_stop"));
  calls.length = 0;
  const expired = sealAccountData({ accessToken, email: "member@example.test", exp: Date.now() - 1 });
  assert.equal((await proxy(new NextRequest("https://franklin.run/api/blockrun/v1/messages", { method: "POST", headers: { ...headers, cookie: `${ACCOUNT_COOKIE}=${expired}` }, body: "{}" }), context)).status, 401);
  assert.equal(calls.length, 0, "expired credit must not reach any gateway");
  assert.equal((await proxy(new NextRequest("https://franklin.run/api/blockrun/v1/messages", { method: "POST", headers: { ...headers, "x-payment": "wallet-signature" }, body: "{}" }), context)).status, 400);
  assert.equal((await proxy(new NextRequest("https://franklin.run/api/blockrun/v1/messages", { method: "POST", headers: { ...headers, origin: "https://evil.example" }, body: "{}" }), context)).status, 403);
  assert.equal(calls.length, 0);
  reply = () => Response.json({ error: "credit_exhausted" }, { status: 402 });
  assert.equal((await proxy(new NextRequest("https://franklin.run/api/blockrun/v1/messages", { method: "POST", headers, body: "{}" }), context)).status, 402);
  assert.equal(calls.length, 1, "credit refusal is never retried on the wallet gateway");
  calls.length = 0;
  reply = () => Response.json({ status: "completed" });
  await proxyGet(new NextRequest("https://franklin.run/api/blockrun/v1/videos/generations/job?token=signed", { headers }), { params: Promise.resolve({ path: ["v1", "videos", "generations", "job"] }) });
  assert.equal(calls[0].url, "https://api.blockrun.ai/v1/videos/generations/job?token=signed");
  calls.length = 0;
  for (const chain of ["evm", "solana"]) await proxy(new NextRequest("https://franklin.run/api/blockrun/v1/messages", { method: "POST", headers: { "Content-Type": "application/json", "x-franklin-payment": "wallet", "x-blockrun-chain": chain, "x-payment": "signature" }, body: "{}" }), context);
  assert.equal(calls[0].url, "https://blockrun.ai/api/v1/messages");
  assert.equal(calls[1].url, "https://sol.blockrun.ai/api/v1/messages");
  assert.equal(new Headers(calls[1].init!.headers).get("authorization"), null);
  console.log("account routes: PKCE login, state binding, encrypted callback, SSE, rail isolation, expiry, CSRF, polling and both wallets passed");
} finally { globalThis.fetch = originalFetch; }
